### ISSUE TITLE
Image Panning

### ISSUE THREAD

**Issue by DrMopp** [rocksdanister/rain#25]
Whole image moves both laterally and vertically regardless of background image used.  Is this intentional?

**Comment by rocksdanister** [comment]
<img width="335" alt="image" src="https://github.com/rocksdanister/rain/assets/17554161/deeb636a-77f0-409b-8349-01e628e73681">

**Comment by DrMopp** [comment]
Thanks for response but Image moves whether the 'panning' box is checked or not.  When in debug, checking 'panning' control only causes image to zoom in/out.

**Comment by rocksdanister** [comment]
<img width="369" alt="image" src="https://github.com/rocksdanister/rain/assets/17554161/03ed70a5-056f-4793-b47b-c19e7d3aedde">

Its because the selected image aspect ratio and monitor aspect ratio is different, so image is cropped or filled. 

Change `Scaling` from `fill` to `stretch` which will distort the image or use correct size image.

**Comment by DrMopp** [comment]
Image is 2560x1440,  screen res is 2560x1440 makes no difference., and movement occurs with any background image.

**Comment by rocksdanister** [comment]
Can you show a screenshot/video of the problem.

**Comment by DrMopp** [comment]
I do have a video but can't get it under 10MB!

**Comment by rocksdanister** [comment]
https://handbrake.fr/

**Comment by DrMopp** [comment]
Thanks for the link - video attached


https://github.com/rocksdanister/rain/assets/97247888/8fcbc31f-093f-4667-98d1-0f0e6fed817d

**Comment by rocksdanister** [comment]
Does it still happen with parallax set to 0.

**Comment by DrMopp** [comment]
No, it doesn't.  Thank you for speedy resolution.
